# ========================
# HandleLocations Settings
# ========================
lang:
  locations-title: '&3&lPublic Locations:'
  player-locations-title: '&3&lPrivate Locations (&f{0}&3&l):'
  locations-item: '&f{0} &7({1}: {2}, {3}, {4})'
  no-locations-set: '&7There are no locations set.'
  no-locations-to-show: '&7There are no locations to show.'
  location-set: '&2The location &f{0} &2was set to your current location.'
  player-location-set: '&2The location &f{0} &2was set for &f{1}&2.'
  location-set-usage: '&f/{0} {1} [<player>:]<location>'
  location-unset: '&2The location &f{0} &2was unset.'
  player-location-unset: '&2The location &f{0} &2unset for &f{1}&2.'
  location-unset-usage: '&f/{0} {1} [<player>:]<location>'
  teleporting-to-location: '&2Teleporting to location &f{0}&2...'
  teleporting-to-player-location: '&2Teleporting to &f{0}&2''s location &f{1}&2...'
  teleporting-other-to-location: '&2Teleporting &f{0} &2to location &f{1}&2...'
  teleporting-other-to-player-location: '&2Teleporting &f{0} &2to &f{1}&2''s location &f{2}&2...'
  location-teleport-usage: '&f/{0} {1} [<player>] [<player>:]<location>'
  location-not-found: '&4The location &f{0} &4wasn''t found.'
  player-location-not-found: '&4The location &f{0} &4wasn''t found for &f{1}&4.'
