# ===============
# Handle Settings
# ===============
actions:
  prefixes:
    cmd-as-console: '[cmd_as_console]'
    cmd-as-player: '[cmd_as_player]'
    cmd-as-op: '[cmd_as_op]'
    msg-as-console: '[msg_as_console]'
    msg-as-player: '[msg_as_player]'
    msg-to-console: '[msg_to_console]'
    msg-to-player: '[msg_to_player]'
    action-package: '[action_package]'
misc:
  line-splitter: '\\n'
lang:
  reload: '&2{0} &fv{1} &2was reloaded.'
  version: '&3{0} &fv{1} &3(by {2}) is enabled.'
  command-usage-title: '&3&lCommand (&f/{0}&3&l):'
  command-usage-item: '&f/{0} &7- {1}'
  no-commands-to-show: '&7There are no commands to show.'
  no-command-permission: '&4You can''t run that command.'
  no-permission: '&4You can''t do that.'
  player-not-found: '&4The player &f{0} &4wasn''t found.'
  sender-not-player: '&4Only players can use that command.'
